apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jellehelsen
    provider: github
    repository: golang-http
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: jellehelsen-golang-http
  namespace: jx
spec:
  httpCloneURL: https://github.com/jellehelsen/golang-http.git
  org: jellehelsen
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: golang-http
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/jellehelsen/golang-http
